# Generated by Django 3.1.7 on 2021-04-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='isBooked',
            field=models.BooleanField(default='null'),
        ),
    ]
