# Generated by Django 3.1.7 on 2021-04-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20210405_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_time', models.DateTimeField(default='')),
                ('booking_end_time', models.DateTimeField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.table'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dateTime',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.datetime'),
        ),
    ]
