# Generated by Django 3.1.7 on 2021-04-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_numpeople'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='numPeople',
            new_name='guests',
        ),
    ]
