# Generated by Django 3.1.7 on 2021-04-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20210408_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
    ]
