# Generated by Django 3.1.7 on 2021-04-08 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('bookings', '0008_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=datetime.date(2021, 4, 8), on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
