# Generated by Django 3.1.7 on 2021-04-08 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20210408_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='booking_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 8, 18, 49, 676673)),
        ),
        migrations.AlterField(
            model_name='datetime',
            name='booking_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 8, 18, 49, 676647)),
        ),
    ]
