# Generated by Django 3.1.7 on 2021-04-08 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20210408_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateTime',
            field=models.ForeignKey(default=datetime.datetime(2021, 4, 8, 8, 19, 28, 160356), on_delete=django.db.models.deletion.CASCADE, to='bookings.datetime'),
        ),
        migrations.AlterField(
            model_name='datetime',
            name='booking_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 8, 19, 28, 160096)),
        ),
        migrations.AlterField(
            model_name='datetime',
            name='booking_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 8, 19, 28, 160070)),
        ),
    ]
