# Generated by Django 3.1.7 on 2021-04-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20210408_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateTime',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.datetime'),
        ),
        migrations.AlterField(
            model_name='datetime',
            name='booking_end_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='datetime',
            name='booking_start_time',
            field=models.DateTimeField(default=''),
        ),
    ]
