# Generated by Django 3.1.7 on 2021-04-08 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20210408_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateTime',
            field=models.ForeignKey(default=datetime.datetime.now, on_delete=django.db.models.deletion.CASCADE, to='bookings.datetime'),
        ),
    ]
