# Generated by Django 3.1.7 on 2021-04-08 08:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_auto_20210408_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateTime',
            field=models.ForeignKey(default=datetime.datetime(2021, 4, 8, 8, 24, 23, 425049), on_delete=django.db.models.deletion.CASCADE, to='bookings.datetime'),
        ),
    ]
