# Generated by Django 3.1.7 on 2021-04-08 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20210408_0827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookingDateTime',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='dateTime',
            new_name='bookingEndTime',
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingStartTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
