# Generated by Django 2.1.4 on 2021-03-30 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fName',
        ),
        migrations.AddField(
            model_name='user',
            name='lName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
