# Generated by Django 3.1.7 on 2021-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210505_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menutype',
            field=models.CharField(default='Lunch', max_length=50),
        ),
    ]
