# Generated by Django 3.1.7 on 2021-05-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210511_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menutype',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='L', max_length=50),
        ),
    ]
