# Generated by Django 2.1.4 on 2021-03-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210330_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
