# Generated by Django 3.1.7 on 2021-05-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210511_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menutype',
        ),
    ]
