# Generated by Django 2.1.4 on 2021-03-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210330_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lName',
            new_name='Last Name',
        ),
    ]
