# Generated by Django 2.1.4 on 2021-05-02 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210330_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingStartDateTime', models.DateTimeField(
                    default=datetime.datetime.now)),
                ('bookingEndDateTime', models.DateTimeField(
                    default=datetime.datetime.now)),
                ('guests', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[
                 ('E', 'Entree'), ('M', 'Main'), ('D', 'Dessert'), ('+', 'Extra(s)')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('maxCapacity', models.IntegerField()),
                ('isBooked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='mealorder',
            name='order',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Menu'),
        ),
        migrations.AddField(
            model_name='mealorder',
            name='table',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Table'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, to='app.Table'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='app.userProfile'),
        ),
    ]
