# Generated by Django 2.1.4 on 2021-05-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210517_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='InVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('booking', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.IntegerField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
