# Generated by Django 2.1.4 on 2021-05-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210502_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealorder',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Menu'),
        ),
    ]
