# Generated by Django 2.1.4 on 2021-04-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[
                 ('E', 'Entree'), ('M', 'Main'), ('D', 'Dessert'), ('+', 'Extra(s)')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealorder',
            name='user',
        ),
        migrations.AddField(
            model_name='mealorder',
            name='order',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, to='mealordering.Menu'),
        ),
    ]
